version: "3.9"

services:
  db:
    image: postgres:16
    container_name: smart_home_db
    restart: always
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: smart_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: smart_home_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  # seed:
  #   build: .
  #   container_name: smart_home_seed
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   command: >
  #     sh -c "sleep 1 &&
  #            python seed.py"
  #   restart: "no"

volumes:
  db_data:
